const movies = [
    {
        bannerImage: "https://etnomedia-cache.cdnvideo.ru/etnomedia/test/videos/2025/21324/images2104747066.jpg",
        cardImage: "https://manascinema.com/files/default/image?hash=0b8a6db22497b498a671acff042b7e76&width=400&webp=0",
        name: "Апакай куйоо бала",
        releaseDate: "03.10.2024",
        rating: 5,
        description: "Комедийная история о столкновении традиций и современных взглядов.",
        genres: ["Комедия"],
    },
    {
        bannerImage: "https://st.weblancer.net/download/4465311_935xp",
        cardImage: "https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/84934543-5991-4c93-97eb-beb6186a3ad7/600x900",
        name: "Joker",
        releaseDate: "03.10.2024",
        rating: 4,
        genres: ["Триллер", "Драма"],
        description: "История о падении обычного клоуна в бездну безумия.",
    },
    {
        bannerImage: "https://zastavki.gas-kvas.com/uploads/posts/2024-09/zastavki-gas-kvas-com-lykm-p-zastavki-k-serialu-dekster-2.jpg",
        cardImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpgXxIwYEqXRkXTOhXXqpDWeP7LtDhh0jwyQ&s",
        name: "Dexter New Blood",
        releaseDate: "03.10.2024",
        rating: 2,
        genres: ["Триллер", "Драма", "Детектив"],
        description: "Возвращение культового маньяка, скрывающегося под личиной обычного человека.",
    },
    {
        bannerImage: "https://etnomedia-cache.cdnvideo.ru/etnomedia/test/videos/2025/21311/images7529968345.jpg",
        cardImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoyb5D40pmXx3tLwnJSfLo_yv6jR5Nz8thSQ&s",
        name: "Мамаша",
        releaseDate: "03.10.2024",
        rating: 4,
        genres: ["Комедия"],
        description: "Весёлая история о сильной женщине, воспитывающей детей в суровых условиях.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/EXeTwQWrcwY/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/51zUbui+gbL._AC_.jpg",
        name: "The Dark Knight",
        releaseDate: "18.07.2008",
        rating: 5,
        genres: ["Экшен", "Криминал"],
        description: "Бэтмен сталкивается с Джокером в борьбе за душу Готэма.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/sY1S34973zA/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/41+eK8zBwQL._AC_.jpg",
        name: "The Godfather",
        releaseDate: "24.03.1972",
        rating: 5,
        genres: ["Криминал", "Драма"],
        description: "Сага о семье Корлеоне и их влиянии в мире мафии.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/YoHD9XEInc0/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/51xJrZeD6yL._AC_.jpg",
        name: "Inception",
        releaseDate: "16.07.2010",
        rating: 5,
        genres: ["Фантастика", "Триллер"],
        description: "Вор, проникающий в сны, получает шанс на искупление.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/6hB3S9bIaco/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        name: "The Shawshank Redemption",
        releaseDate: "14.10.1994",
        rating: 5,
        genres: ["Драма"],
        description: "История о надежде и дружбе в суровых условиях тюрьмы.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/5PSNL1qE6VY/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
        name: "Avatar",
        releaseDate: "18.12.2009",
        rating: 4,
        genres: ["Фантастика", "Приключения"],
        description: "Человек оказывается на планете Пандора и влюбляется в её народ.",
    },
    {
        bannerImage: "https://i.ytimg.com/vi/tmeOjFno6Do/maxresdefault.jpg",
        cardImage: "https://m.media-amazon.com/images/I/81k3B0N5lJL._AC_SY679_.jpg",
        name: "Interstellar",
        releaseDate: "07.11.2014",
        rating: 5,
        genres: ["Фантастика", "Драма"],
        description: "Команда исследователей отправляется за пределы галактики в поисках нового дома для человечества.",
    }
];
